# Generated by Django 4.1 on 2023-02-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_alter_dish_options_alter_dishtype_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(max_length=1024),
        ),
    ]
